---
- name: Ping the website
  hosts: localhost


  tasks:

  - name: Print the website
  debug:
    msg: "The website is: {{ url }}"

  - name: Ensure website is reachable
    ansible.builtin.uri:
      url: "{{ url }}"
